### PR TITLE
WIP: Feature/gui project search

### PR DESCRIPTION
**Pull request by JasbirShah**
**Changes**

This pull request adds searches to projects and configurable search settings to the graphical user interface. It may sound small but the changes involved are huge, they also require significant changes to how we update the GUI to avoid multithreading issues.

- [ x ] Icon support for the project tree
- [ x ] Add search to project
- [    ] Multi-objective algorithm support
- [   ] Configure search parameters
- [   ] Fix issues displaying output

### CODE REVIEW

**Comment by ScottWalkerAU** [comment]
Conflicts need resolving first. Merge develop into this branch and resolve

**Comment by ScottWalkerAU** [comment]
@JasbirShah What is the status of this? Looks like it'll change a bit of the GUI so not sure if attempting new work will conflict with what you're doing.

**Comment by JasbirShah** [comment]
Woops, I completely forgot to check my notifications... So about this branch, WIP branches aren't ready for merging and the PR just exists to keep track of progress.  

This branch does have a lot of major GUI changes, but if you're concerned about conflicts don't worry about them. Once I get back on this I'll do some house cleaning and perhaps break this branch into several smaller ones so the conflicts are more manageable.

**Comment by JasbirShah** [comment]
I've pruned this branch and moved it to a new one with up-to-date develop changes.

**Pull request closed without merging**
