### PR TITLE
Search Pausing

### PR DESCRIPTION
**Pull request by ScottWalkerAU**
**Changes**
* Searches can now be paused and resumed from the current spot
* When a search is paused, you are able to change the mutation rate, crossover rate, number of generations, and which blocks are enabled/disabled
* Statistics update accordingly, such as time elapsed
* Fix a memory issue where if a the dataset is changed for a search configuration whilst a search is already running, the search doesn't stop.

### CODE REVIEW

**Comment by ScottWalkerAU** [comment]
[Make search log, progress over time and results list persist after search is stopped](https://trello.com/c/ogfFQbLM/255-make-search-log-progress-over-time-and-results-list-persist-after-search-is-stopped)

**Comment by jayden626** [comment]
@ScottWalkerAU What do you mean by "Fix a memory issue where if a the dataset is changed for a search configuration whilst a search is already running, the search doesn't stop."

Does this mean if we are running a search, then go back to define search and change some details (such as crossover rate), it will stop the search with no option to resume?

**Comment by ScottWalkerAU** [comment]
If you swapped datasets which a search still running, using the same configuration setting, ie, changing the dataset in the drop-down, the search could never be retrieved and ran forever even after the GUI was closed

**Comment by lachiesainsbury** [comment]
Only minor issue I can see is:
1. Add 2 new searches, but only add a dataset for one of them.
2. Start the search which you've added a dataset to.
3. Then click on the search which you havn't added a dataset to.
4. Observe that the search progress statistics and graph don't match the newly selected search, they contain data from the other search you just started.

Such a tiny issue it's probably not even worth a fix if we're just presenting videos anyway. I'll approve the PR and you can decide whether you want to try fix or just merge it in.

**Pull request merged**
