### PR TITLE
Feature/preprocessing

### PR DESCRIPTION
**Pull request by lachiesainsbury**
**Changes**
* Transformations now stored to support future reversal
* Transformations can now be unapplied
* Modified text now appears next to each feature that has had transformations applied
* HandleMissingValues supported from GUI
* Offset supported from GUI (still needs tweaking)

Still need to make some more changes on the pre-processing tab but I wanted to merge in my current changes before I get too far behind develop.

### CODE REVIEW

**Comment by lachiesainsbury** [comment]
**Merge conflicts**
* For now, I've reverted a few List<> declarations back to ArrayList<>. Some methods in the DataManager and WorkspaceController are still using ArrayList, so I will convert them all to List<> in a patch soon. This merge would be a pain if I converted them now.


I also need to temporarily disable the OffsetTest class until some changes are made within Offset. Any way I can do that from the online editor? If not, I'll just make a new patch once this PR goes through.

**Comment by ScottWalkerAU** [comment]
You can push the fixes to this one, just make sure you make another to generalise the use of ArrayList to List.

**Comment by ScottWalkerAU** [comment]
@lachiesainsbury Did you check this?

**Comment by lachiesainsbury** [comment]
@ScottWalkerAU Yep, it works fine for me after those changes. Seems like the list of features is reset or something after hitting the start search button, as the 'modified' tags also disappear. I will look into this further, but it's at least functional after your fix.

**Pull request merged**
